AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template is partially managed by Amazon.Lambda.Annotations (v1.0.0.0).
Parameters:
  DbConnectionStringParam:
    Type: String
    Default: Server=my-sqlserver,1433;Database=MyECommerceApp;User ID=sa;Password=Sqlserver123$;MultipleActiveResultSets=true;TrustServerCertificate=True;
Globals:
  Function:
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: myecommerceapp
        POWERTOOLS_LOG_LEVEL: Debug
        POWERTOOLS_METRICS_NAMESPACE: myecommerceapp
        POWERTOOLS_LOGGER_LOG_EVENT: true
        POWERTOOLS_LOGGER_CASE: CamelCase
        DbConnectionString:
          Ref: DbConnectionStringParam
        TopicArn:
          Ref: SNSTopic
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "myecommercetopic"
  MyECommerceAppClientRequestsHostFunctionRegisterClientRequestGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.Host.Function_RegisterClientRequest_Generated::RegisterClientRequest
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /client-requests
            Method: POST
  MyECommerceAppClientsHostFunctionRegisterClientGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Clients.Host.Function_RegisterClient_Generated::RegisterClient
      Events:
        RootEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
            FilterPolicy:
              event:
                - clientrequestapproved
            SqsSubscription: true
  MyECommerceAppClientRequestsHostFunctionListClientRequestsGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.Host.Function_ListClientRequests_Generated::ListClientRequests
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /client-requests
            Method: GET
  MyECommerceAppClientRequestsHostFunctionApproveClientRequestGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName:
              Ref: SNSTopic
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ClientRequests.Host.Function_ApproveClientRequest_Generated::ApproveClientRequest
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /client-requests/{clientRequestId}/approve
            Method: POST
  MyECommerceAppClientsHostFunctionGetClientsGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Clients.Host.Function_GetClients_Generated::GetClients
      Events:
        RootGet:
          Type: Api
          Properties:
            Path: /clients/{clientId}
            Method: GET
  MyECommerceAppProductsHostFunctionRegisterProductGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Products.Host.Function_RegisterProduct_Generated::RegisterProduct
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /products
            Method: POST
  MyECommerceAppProductsHostFunctionEnableProductGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Products.Host.Function_EnableProduct_Generated::EnableProduct
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /products/{productId}/enable
            Method: POST
  MyECommerceAppShoppingCartHostFunctionAddProductToShoppingCartGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ShoppingCart.Host.Function_AddProductToShoppingCart_Generated::AddProductToShoppingCart
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /shopping-cart
            Method: POST
  MyECommerceAppOrdersHostFunctionPlaceOrderGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName:
              Ref: SNSTopic
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.Orders.Host.Function_PlaceOrder_Generated::PlaceOrder
      Events:
        RootPost:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  MyECommerceAppShoppingCartHostFunctionCleanShoppingCartGenerated:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet6
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      PackageType: Zip
      Handler: MyECommerceApp::MyECommerceApp.ShoppingCart.Host.Function_CleanShoppingCart_Generated::CleanShoppingCart
      Events:
        RootEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic
            FilterPolicy:
              event:
                - orderregistered
            SqsSubscription: true
